<?php

namespace AppBundle\Repository;

/**
 * TuristicPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TuristicPlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
